# Generated by Django 6.0.3 on 2026-03-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Fazcodeapp', max_length=100)),
                ('active_theme', models.CharField(default='sb_admin', max_length=50)),
            ],
        ),
    ]
