# Generated by Django 6.0.3 on 2026-03-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Administrator'), ('OPERATOR', 'Operator'), ('USER', 'Regular User')], default='USER', max_length=20),
        ),
    ]
