# Generated by Django 6.0.3 on 2026-04-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_judul', models.CharField(help_text='Teks kecil di atas judul utama', max_length=200)),
                ('judul_utama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('gambar_bg', models.ImageField(help_text='Ukuran rekomendasi 1920x1080', upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Urutan tampil')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
