# Generated by Django 6.0.3 on 2026-04-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_heroslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='logo',
            field=models.ImageField(default='hero/logo.png', help_text='Ukuran rekomendasi 1:1', upload_to='hero/'),
            preserve_default=False,
        ),
    ]
