# Generated by Django 6.0.3 on 2026-04-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_heroslider_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamaWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_web', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('google_maps_url', models.TextField(help_text='Masukkan link iframe src dari Google Maps')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
