# Generated by Django 6.0.3 on 2026-04-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_namawebsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListHarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=100)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('satuan', models.CharField(choices=[('meter', 'Meter'), ('unit', 'Unit'), ('pcs', 'Pcs'), ('set', 'Set')], default='unit', max_length=20)),
                ('per_hari', models.BooleanField(default=False, help_text='Centang jika harga berlaku per hari')),
                ('harga', models.DecimalField(decimal_places=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'List Harga',
                'ordering': ['-created_at'],
            },
        ),
    ]
